#define SAXPY_KERNEL saxpy_cudaDMA_brucek
#define CTA_COUNT 1
#define COMPUTE_THREADS_PER_CTA 32 * 2
#define DMA_THREADS_PER_LD 32 * 1
#define NUM_ITERS 2
#define DMA_SZ 4 * COMPUTE_THREADS_PER_CTA
#define BYTES_PER_DMA_THREAD DMA_SZ / DMA_THREADS_PER_LD
#define EL_SZ 32
